apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres-secret
    namespace: keycloak
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:9qsccD2VO88=,iv:FoDR3i+eGQtZTbDVGZ3Ed265uMPe6C26I2OER2ttMXg=,tag:pdI9dUDMeY/+3f5uxlShgQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:pnM7pFCdY0o=,iv:ddK5PlnpW3hwtG4X2A0rGZF2n7vlTNWarO3qlOnr1uQ=,tag:Er1QPjqT6+qRnihYz4Ln4g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:UEdJKVZQfvdmZjkrTD3I+lNRo+JDi/LMO8YDHenrhkQ=,iv:+m09mdBjpw1zm2CZYbwH/jAUmABC7oiZWBioMoO6hE0=,tag:vVPRKs/qH173MjFFckZLtg==,type:str]
    KC_DB_USERNAME: ENC[AES256_GCM,data:IzCI7WrwTYg=,iv:f04wisijOL3qUnYkUy9vvCrMAuj34hur+dfTAiC7CyQ=,tag:PdRfR7fyIeEE34By4mJugA==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:AkR+b2i4T7SmAhXnuVulZ7DP1LfJ1tEcyE1M2Sf4QLI=,iv:D4NK+lAlMYeIj7JvrvH6wpZUojCVvuFj9a6nh8ruMe8=,tag:Y07K2R21v5D0lUY56IO9ZA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT1RCNXFiVU9iU3JlR21X
            R0pOTlM4ZXBDVE1vMkpEbS9MS1gyeENibTBBCm90b2VlN0xlWUlHOXJYeDQ1bWtW
            VG4yZjRJMjhsb1NTK3JxWmdTUUsrOEkKLS0tIGFuRDk5T1AyakZqcWlTaUNQcDRw
            cnlqODNyUGo0MWxYekhOZWFuRUhCMGcKIp55n8p+Rbih9QYTNmzJHeK1W7vzI0VA
            nT9mtaoBQm14sTNYjhzMLcEdAgwG1F92XXJoos4B1Ed6xFb68JXojw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T10:18:45Z"
    mac: ENC[AES256_GCM,data:Q0CNzUN3c2YMMuBQueEXG6jp8qXvKL4MReRQG4Lmeb8pclms6Df9dwJiVvvkD7WN6QOBNGU0DFDEzEJ/+YMM69ck3BXuoKxUE2yqfbYnz6NAVXDB0sbL5dJ0XZA4HD2AJtZOkuwlsVVaNcdNI2ZbMjwMQ7GHEqBoVisvlWeO8T8=,iv:R7J0oj9PdNK5dUY3MDLde9+p2tuyhP8fs5oFOIQWhOU=,tag:GZytu4KYR8Hwd9vnH4NWFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
