apiVersion: v1
kind: Secret
metadata:
    name: keycloak-credentials
    namespace: keycloak
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:AwCsrvn/ZJ8xdvuKXdcjxhC2PEjjvkibI+g+T50s,iv:z4t0I2kzqmZeVm2QQ0ysByK1ePiqlSerBAwlAtef8xA=,tag:gD+MzPhkc/X/zWuQ9WjnLQ==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RnJvN2hUMzBuR2NXdHpH
            Z3lxQ1UrbTBpYUNpdVB5ckJGZ01qVWpTbERZClg2Zk1MUHZsM3QxZDhlTjV1ZU9t
            bFFnVFVMVWcwQk5ucUtNWFJuUkg3ZUUKLS0tIFQwdFRveDlFdS9XU2lrK0ZIdVhq
            ektRRWZqS1RNZXk1OSs0K242ZHJHSmMKmWkNKufwklsd53LSWN/OP/nXNpWEYHUI
            6iOzQK941nliz2JTS8RFUWpdvefK0RRnOGanq+dOPT0cBc9qrvHsEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T14:55:40Z"
    mac: ENC[AES256_GCM,data:7A07K8a+jQmRzZ9OubGIR+Bt8lkxABOdHlCczlCvhj2mGd0fF39jEYnAS9aNDaMAkoB1dNsw7FH1G9tIql5Xc/hVunGSQi0M6qlk6t+TY/iw+Nx+KBZHQxQUtDGwBSF/rc5n4l/ZnVMeYKfQi9jMW/qP0FiTfmwnontV7Y9BuAk=,iv:yG8zrRUZCR732P1CQd6Kx8cz1mcQZvZFpcMkP+ovwa8=,tag:++YS0hUTEzmnZ7D0+OvXGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
