#!/bin/bash
cd /home/alex/repos/homelab-demo
echo "# Deployment Process Documentation" > docs/deployment.md
echo "" >> docs/deployment.md
echo "This document was automatically generated by watching the deployment process." >> docs/deployment.md
echo "" >> docs/deployment.md
echo "## Changes Detected" >> docs/deployment.md
echo "" >> docs/deployment.md

last_status=""
while true; do
    current_status=$(git status --short 2>/dev/null)
    
    if [ "$current_status" != "$last_status" ] && [ -n "$current_status" ]; then
        timestamp=$(date '+%Y-%m-%d %H:%M:%S')
        echo "" >> docs/deployment.md
        echo "### $timestamp" >> docs/deployment.md
        echo '```' >> docs/deployment.md
        echo "$current_status" >> docs/deployment.md
        echo '```' >> docs/deployment.md
        
        # Log new files with their content preview
        while IFS= read -r line; do
            status="${line:0:2}"
            file="${line:3}"
            if [[ "$status" =~ "?" ]] || [[ "$status" =~ "A" ]]; then
                if [ -f "$file" ] && [ -r "$file" ]; then
                    echo "" >> docs/deployment.md
                    echo "**New file: $file**" >> docs/deployment.md
                    echo '```' >> docs/deployment.md
                    head -20 "$file" 2>/dev/null >> docs/deployment.md
                    echo '```' >> docs/deployment.md
                fi
            fi
        done <<< "$current_status"
        
        last_status="$current_status"
    fi
    
    sleep 2
done
