apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secret
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:aBijIy2X7yknYK2XXj8wFnDwq1mttkKodvJ1FBFr,iv:bxpejgR5yL34UjECKf8X3t/LV89YHifQzSx9HlErWI4=,tag:LxK6F7d17RN+F0z1rN/y9A==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:gwYCvM7THXh2,iv:gpK+Jn1TmkZfnHSLqRfKT9git9FXTiINYFEPDCdaa88=,tag:BN91KMJ2ctgd3HrrYZZIRQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:GerSp09MXdVS5S2IIAfni9GZvxQR6CMySio1Vp+4,iv:6FSimsB5kDna5jbmG7IrFd2EXWKJhF6uKKccpDRJQUc=,tag:k3qQVSPM3EsrCDztYIVWAQ==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcnl1OUdSNlVxeE1RRWdw
            OURMK1c2T0ZPMUtOZjQzTHEyVGJtV3N2WXlvCnplM0V1RE4rZ0lSb05ZL0pQYU1G
            bWVteElzdlhwZ0dVTWlIdDErRW1kRU0KLS0tIDVVQlZ2VWE1Ti9SNXBadHB4T05i
            cWdYUVg3Nk1LOWlaOFJYUXYwNmVxQzgKePSX+7MxRM6znZ5wFk/IaShOmHKwHOx7
            KaOK2a98GzM+XBHYaRE6DU7S42gi3PBQPLN1JWZlw1TUbKkBxD/qsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T10:08:32Z"
    mac: ENC[AES256_GCM,data:itoEkUnYVS/2w3ITF6GF1pRJNgIGJqUbqTdH2eKpLkSDdUJ9iWWwSfhLRNmKeoz815zscVS03reDp1sS6l2GdgRm5siFRCB2e7IHnKepz2qFY1/gig6TctqD5EtFomDhSL1XmEWL0ji7Swk+DuD6VHVuUifXi+mssQvWShSkjhw=,iv:iJnuvidOjdhzuf8/bvf4mRTkd73f7Pl1EcteiqUDDts=,tag:INWjkJuUI+W/V6dBV11s7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
