apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:hzXuSMzb8T1B3ynkqHSy00LYrmumoVup0dWYLZQ7Uiu940zIgwtxqHctjhcUAQw/Z+D/rd8=,iv:LsfkDQn/P5IBR3Dxc8MfgI9x3CGpz9so9VuWFnPJVgI=,tag:BXVoRmjvSzFNxwZczCUA6A==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dWNIcVNLUjR1eTN1bW5U
            RUpYa1FSREVTQ29STTIxdHhNbWZYcDVnNnhFCm9jVElZYXJWdE4xNDlEUlo2TzZl
            dVFDeUZRTDdaNHQ2OFdXeEw0MkJUWG8KLS0tIDZybFZRZFN0MGVZMEcwQVpBNS9E
            VHkzL0RJZjBPTXVhWE9rcTlad3R3clEK3MmtQTVyqEe3sO+xDdqrmsOmo+ZHxHHB
            1KD6QKkh1ZjgjD7+xPpBO7QdT2ix7tsl/x4TmdMi0MY4YmRbtAKLPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T17:06:14Z"
    mac: ENC[AES256_GCM,data:lCgqlAVkUuOMotj2b92idUCF7V/koESgeT+4/ofI3R9B3xcwHnkzkOAO0INSNF8nl5HWQP06F9cwNdSoSVmCs2TgVPzcSF6o5CCkuv6bf228lJePbrefpF6zoBeVloXmtBy+dWuAnQzXtEy+wa5cgqe4ouSzP++M3T0kA4fNKdU=,iv:2DSbHJKZxvWIHBLw8Vh2z3TIz+UMtSz1SUTG5KVrqpc=,tag:YSCitpCybzcIhPAJWdBm3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
