apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:gYiM3xm2zGzzpzePyx+K9rYy5f8EzMdR/wdDLI0Dq2uc8jdbv+0ZaA==,iv:rZQPz6jqEz3Oa8Ood6QsanitS75YuLvjVub4i55YDyo=,tag:3TRoyLD9OeT6hHSgqh9dJw==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTEJQRGxDZSs1d1YvWVU2
            aGVJM3Byb2tic2loS1ZlZlNuMGJBNzlqVms4CmUvZ3Iwa0VoL0FuU3FVWGtyTmJk
            bzNHWmNBMVBLSlo4ZUdvNUF4blVjZmMKLS0tIGMrZ3I5U1ZHaUtSV2xydzdnaUl4
            T28wRUUyVVFhYlh5N1hyeXJ3aTduNFEKLOgVYI7IYYWHjaAYFMnGkLh+0iuhGX9/
            x32sKwdN3Y5M+cenxBJEz1toGn1VAlJXlTuGvhnoAmqK481fdjK3mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:37:40Z"
    mac: ENC[AES256_GCM,data:LHvEZ6pRGP09qzP7Sqce0gWViDWCGJ0m5+PMTLA8gv8bt+91eD1N3H5GVusTIKUpLMNMmosOg/YnMYyUaMcNZsVR0K1yQ3ldzJzej9s4q+OQ2vRzryzXlavs08NPiu8cE1FkZCt1Y6Q28XFX5jpA987yQI6BiQlHkMyhKyhpnrU=,iv:VVZOIYbz/6s17T5/XV/hgjXL2GIvZdDdG5ll7tx91SE=,tag:ptolbtPlBPwvfTSlQ9bEhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
