apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-hetzner
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alexander.benisch@gmail.com
    privateKeySecretRef:
      name: letsencrypt-hetzner-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.hetzner.com
            solverName: hetzner
            config:
              tokenSecretKeyRef:
                name: hetzner-secret
                key: token
