apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:vzAoCIZfwK1w5A90LJGKVxuMNMlTa/vAupbofXULVtqnDNVHlDX6v9BDhvg8zlmGZy3pfsV2F1DLxk0fZJp0ag==,iv:3wBDU4Cs+AiTClgRjvpEmaO2KLSbRbk41nflrBFlSZ8=,tag:sGdHK84u+tnC7Pey8bpwSA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUlV6TVF1c2F0bUpsSWZK
            WHByZ1VOWFlMaFNJd1hhVFV2L3liWXpmYkZjCk9aNHpPalVjbEQwRXJWZGNvRjk5
            d3VVcTJ4U2g2TUVaM1Z5Y1BwL0UrT1UKLS0tIHB4Q2JVODMxUUlSUUxSL1Axc2ts
            cFpvWWM5YUt3dGFnNnpFdG1HcW5nZDQK5xi5wPK2URygJkCnuy/lhpMMCm0m11PD
            kJmUbSWrBoHgGrN7r9jVHaWVTTiIzz8q1eMQcq2HQMYnoU4YrNY2qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T13:47:43Z"
    mac: ENC[AES256_GCM,data:FXZvZ6kx3Y4jm35/KMHXfHpp3rXradSgjyVaj7cyg/s14j6iJRDEb86pZL/9p8H9rrncn18u6bja7f4pA00lWvYoYz9POrVoacJjFoYjkvl0O8EA4VpDAGrhoDRWh7hE0QzxxJU90JsyiF7pr8QdnUKmtv7hv8qJ0g3EKU8X8tw=,iv:Sw0YejA/rGjG/dQ0Hybj+H9ioN4QnY3ZYU+bOovbWhA=,tag:0RMCaQo1a0MFK3Q1RjlEhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
