apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-hetzner
        namespace: cert-manager
      interval: 12h
