apiVersion: v1
kind: Secret
metadata:
    name: no-deposit-django
    namespace: no-deposit
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:2HYxHztNzcLuilgv6Zk08ZXEVXxi8SNm66Z1Q4xiavx0YWsoUMm1DVgCD51h/ip+RkI=,iv:orVlHF4nl+eOpOu8NFy9zr/7p+Tf3K+Hw4qb4BmIUZI=,tag:XPoKrvldC6Z4l1hH3LDmWg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:yCrdKPQsuG+bT1TbgxqiH/QX5A==,iv:btSOFek00ScE3+yYPfBlYUGRTo8gvTEAOiR4C0itDZc=,tag:Bz4766mDu4NIV7bM//ObjA==,type:str]
    OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:Voq+9iPi4sLbphHy13w7rRP9ien7kQHMDCXcxk76XiU=,iv:cE+pXsKZMCLgEOrFQs8B4Z30ze3wiRF/VXOjLJ1pHbY=,tag:XtgzMsEUssBndJnuiI3aZw==,type:str]
    HETZNER_OBJECT_STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:OUKT87LaE/iYhG5VW8eedPoZeqk=,iv:esUqHIV07tHlyYHQ3RF8vgya3r/Nrwl1HbFS8UVAMXQ=,tag:T1offAm1k0100iKEX96BMw==,type:str]
    HETZNER_OBJECT_STORAGE_SECRET_KEY: ENC[AES256_GCM,data:b1ifNqzflAfBR4bYqAn0rDuZApvhLn+487Ee6SpkfC1WVlRuG9O3pA==,iv:ceibpVxqqrxOGhLFgwFhkF2wRXukoUyODG/MZby1+eA=,tag:G+tIm6Ts6ze1ER5E2y7ysA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjejV5RFdhTllRZWpyS0pY
            VmRyL29XQ1dQMGoxOEpmQmxZMlBnNjk0VG00CjZmQzhrZ1hibVZHbkxYTnF4WVFE
            My8vSWtEcGpXMkFVdEl3RGZNY0NwNFEKLS0tIHhHSCthelVxYmljbmx6d3grZGZN
            TlR1UDBDYUk5Njk5cjRjMHRDbGFHTlkK13GOvgKovXSSeI2wi7R7clpx2YvkRD1X
            VAkMeMnFmggO+fOHkwU/+oc0NyhKPpqDqt5YgsANMVETIb415Yf0jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T11:52:32Z"
    mac: ENC[AES256_GCM,data:YyvlwSUkITw3Gu0l5CUoAhQn4sqy1uXN5wdHQ69XcRlPprOVUMxaPBx8/oV/iVFScQDO4n2TbYiwJWh4cRitpojiRMwk3+jNjdfW2rpRv2CN6h8tGZP9Q0Z+tG6Nfy3mY/VHF+ApThlGYU+noXpYyd/nqincEdpEnuWlUXNgGzE=,iv:vHGAD/0QtQIQn9eUjQtBLaJAXR4pcyKfLhKGiwqi6Hk=,tag:ECvLvUgmJH5BVuyTYt1trA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
