apiVersion: v1
kind: Secret
metadata:
    name: no-deposit-oauth2-proxy
    namespace: no-deposit
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:rWE76tWTHp0c/22sEkQ=,iv:EyRbnrsgbPGHApKRvGgf8BWsfzuCsmbqbL6hSr16SRM=,tag:9sZtnXDda/AlDQEz/H2gLw==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:Gl7Iu8edJCvOHKvKiiyOavOcXmnSHZwt9Jy+gnXc9IQ=,iv:hl9hTxqG57H88kt0eADDkV9zcAPHkYMic6PVOiMKpsQ=,tag:e4hGySwHL0g56x2WzLlg1Q==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:anIFF2gjUagRqMMhnkHoeEBn4MlIa0XkouoFhcOADw4=,iv:68LS0TMmG6goeqrNMViMRy9wg11oy6oxoFsvy3TEWYg=,tag:VHBF4IEBs2TgbLgMYlaVow==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:97BM+wOY8ZVcfYy42HDgZl9Glvg//k4kmiP6CE2n,iv:CtiAufC90h7o5WaLYKmP9/FchAISF2YGD3c4CET0l/4=,tag:Hhucc1d3QNRORPw+yEVLtA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINTN2WmpvVUFQVlMrMmg5
            SUVmd0VTMnJNaXhFSWlaYmp4dXdPM0IwL3lBCmRjS2U0dkFqNkdyWWdMcXd3bkxG
            SmhidnQ1K2xUbkFZZHo1SHJ6dzR6T1kKLS0tIDA2WXJEU1pNMzMwM2JYUk1xanVG
            K2p0a2dQQm1EK2FCenlzNzN6U1JxdE0KGaytkfmtvojvksdZ6XJT+KAKTSLncVRN
            YV4OkUvkPmI/TGhP4L+EeVGtCWmQ0JvaHzwsjCH3JmU7yT/H7zPU7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T16:07:32Z"
    mac: ENC[AES256_GCM,data:hbPKLvwbCLP8ND9SVX1HLI1DAvqLELS4DxgqQO/lnOTL3xFzyYed8nm7ju35t6orlvvhN+tRKayVooRgjYmMbs3sfWjzR9KNax0hB/wYIGjtHeIybL4KspF4b6qarNC8wZF7yxrkhHIa/onoD7EJp2OJxrqynhAaVDfungVZocg=,iv:9xu8CLYHXWDFIqjM60NH2vzpUHE0HIVldcpr5/+URh0=,tag:n4S01ngrytS624n5c0e5Xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
