apiVersion: v1
kind: Secret
metadata:
    name: no-deposit-oauth2-proxy
    namespace: no-deposit
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:c4EqvvRoafxdoNmw63E=,iv:7LGbeS1373uTD7kIlM7N4RycRpdIrQXa77Qh64gEEOQ=,tag:CiGqtsPY/e5odidjmYWhUA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:MPriinWEE6TS5RWVL17szSZc09jfzSAP6ZcqYp7VGc8=,iv:3nj+LAokfianXVU1mJ5wYO+gRmE+SWZ1P723DXwBdzo=,tag:Y2iY3LyOgbF6BPnqZXlalA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:5o2oGWHbKn/vg3qIEL88BnWeQAtDELNIV5XpRLp25Is8uwhBxtG331bIY7Q=,iv:rdN7T3r0KtTe2yx4/88dchLOp7LM9ddfbNAsEqfDuk4=,tag:pEmuARtMS2bBFiFu3QVKmQ==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:/1CHL9VwTiGVORkgtnNK44svwSmHBnWWwEWswTGM,iv:IIDYMlT2eUbYh57MkDS9d+iOy2/PrPjVXhUeWsp1z6Y=,tag:4gl/ir3s9WlNlEwx7VCJ7w==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNTVQTmE3eGhTVHVNZjFq
            cWczeEVLUWpOOHhjOXVrdFFSMHA0dzJkMGpZCmxkRlM4RG1JaVNIRU9tQ0s0V2Vu
            M3ZQZWtoOXV1UG5BRGN3ZWlYK2N1ZEUKLS0tIFNlMGhKK3BiYUdVdUd5M1RHVXdw
            cGJ4MllCQmNVL3FzR254TjZwOFBHcGMKYR2+Z2ud62ekTRDKiE8AWwzkMbYWyCcU
            7kkCRtBB7O5KFRk3aRc3m18NkNf+jWIZU9OfbfeTrL4D9Hv6q24WVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T13:26:22Z"
    mac: ENC[AES256_GCM,data:l57eW6PzSbnMCQ3hCl5D4ZF5bDW908StMF+4CQ9zWIyizHDNhRF8HvOGxVzpzDfbJSHUqeYk0fO6C5beFunhj3GGKsaOgaCSD6LrreMPPbABMWD7oh06SPgLCQeGtoBn60LnVQayYPthyxSs926Gp9MtycgFFmvWJMYS2SblfZ4=,iv:TT/1vT/656UEu4xsX/YiiqhUX1WB+RAndmpzx8ZR3n8=,tag:VBFG6oWbqqtntg6bMwwx6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
