# Generated by Django 5.2.13 on 2026-04-12 11:25

import django.db.models.deletion
import guarantees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(default=guarantees.models._default_certificate_number, max_length=50, unique=True)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('claimed', 'Claimed')], default='active', max_length=20)),
                ('document_url', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by_sub', models.CharField(max_length=255)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guarantee', to='properties.rentalapplication')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
