apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-traefik
    namespace: kube-system
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:tZX4Hiuv6IrJ6rDP02/iWB2678Nb03o+NRrYxW2oeF6U8/S5unWbMHyuxe22mUZPFmbQLLw=,iv:4Y6wFkuEYCpywE8RFNtL7Ngea1vUfYsjNXHN3tZZulA=,tag:eXLpyGwnFle0oVdj+toodA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY0F0cGk5UE9iQy9XQU16
            Z3A0RVlxRmFqNmtLZnlSTTMzNERIYUk0aFJVCjVZTkxGaVpBN1FFQ04rRkdpZkVW
            em11dTJOSFBKUjEzS2UxN3B4cWdJdHcKLS0tIHhJL3ZsMTdGTFhwL1Npa0JxTHZQ
            N0hLa2IxSlJyR29mVURmT282WHhGbmsK7GCIlpQtdk0X5wBtGnXkFZ92dqbQJLle
            Skkvc0pnZplYxo2uvTOs6wyzxOMkTRpDtA6/xb+Z5rAvvi3X8Dp90Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T15:19:53Z"
    mac: ENC[AES256_GCM,data:ydOIZAMLk2BQkI282Rw2CilFIAP8WbDn2FhLPZAgrS/YbFFpgrVBbiGq+nQVQu1MaHS0OvDeASCldWsu++ew3X2yWfOnsbzdUfzvGNCEH9vVsPcrYDZ+WlxkMWyDnV7TqYi+AHxlMLKA4/fVQBWkG8CzELTQoXg4AJAAouKwZn4=,iv:SGKqwkGCw+xC/YkdWwulwn3d3xlD7NC5xdGe+QxMT94=,tag:xG2TLqczyy2Ey71VmaG7+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
