apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: nextcloud
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:cwtQM5zp24TY,iv:kJoFF89ZekLT+wQXpLlqj2gBfRn/MGawomLkK6IB6HE=,tag:NfePb2csK/shmOdDKc3tXg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KJUOmYUmXjL5UnQP3b9GqKFss19wqJcVqw==,iv:Vwu4nstSdB6/JyIChwdmpGilaWR5d9OuLBGDpnLNLNg=,tag:lsFtYErEXdEBL9jBCRv12Q==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:TrULlDP+/GZS,iv:No5g4LgjL2yTEZW9/klJknsorFkbAa+A7+2u//ayknE=,tag:RPuYThbAuu4E1MrJ9HhShg==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NkpYZktKZEJYZnJnbHV1
            Ym1oaEx4KzJ1TFZtcDdLYnRHdEt5Z1N1MUZNCi9WekFXVm0wVmZ5ckE1Zmp4aUV3
            YlFjL1I2L3JIM0E4Wld6dVN6am5pV3cKLS0tIGdJYVJ5U1pmelNDOWxveWFxMEJa
            WWdqaVpUdnovclpUbUJsS2dUS2I4YjQKdQCU5LGFmqO9Nfv5UBunttgtWcNbbB4C
            /65vp6zRnLLp1l9/Uk1KcwEaPwB7EgwaVxiPtHob6cEBlgOJUw9o3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T14:49:11Z"
    mac: ENC[AES256_GCM,data:qTxUXhJ5E+Kgq+SYjCwwCljpiZVB5oitw9fthgb1hQRMTNXQL915/o3TZ5eATcBmmt/cdI90C+FwP/Y+zqfKL9bM9yylrkNR/ANr3jv84NAlTfu1GHMAnVxhGYtwcN+g/frx1hCkPLbGg/dAfTn1AHTqYzMtbIJ65X8ER3v/gd0=,iv:OiZHXl78usGm95HxKnxOljcaKeVygJaRV8KzGQBhIWk=,tag:/NKPBZ8n9u+VbzsmbfCseA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
stringData:
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:Xwb+eJA=,iv:PsmGEJgu/cgYjys1bUJvkyvOg0FOzdKxplPE6KvmO8c=,tag:1KlBa+2hNRsUGdExbpdKDA==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:6mr1gFYchL7Xn6/jwCvYoBiOpHHVDiybwQ==,iv:nu/cO6a0al5eh/FsJlzdGuKA7DC7N4wI3iVuPmL7jZw=,tag:8E8ZrpJa31txrXzy8zz0pw==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NkpYZktKZEJYZnJnbHV1
            Ym1oaEx4KzJ1TFZtcDdLYnRHdEt5Z1N1MUZNCi9WekFXVm0wVmZ5ckE1Zmp4aUV3
            YlFjL1I2L3JIM0E4Wld6dVN6am5pV3cKLS0tIGdJYVJ5U1pmelNDOWxveWFxMEJa
            WWdqaVpUdnovclpUbUJsS2dUS2I4YjQKdQCU5LGFmqO9Nfv5UBunttgtWcNbbB4C
            /65vp6zRnLLp1l9/Uk1KcwEaPwB7EgwaVxiPtHob6cEBlgOJUw9o3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T14:49:11Z"
    mac: ENC[AES256_GCM,data:qTxUXhJ5E+Kgq+SYjCwwCljpiZVB5oitw9fthgb1hQRMTNXQL915/o3TZ5eATcBmmt/cdI90C+FwP/Y+zqfKL9bM9yylrkNR/ANr3jv84NAlTfu1GHMAnVxhGYtwcN+g/frx1hCkPLbGg/dAfTn1AHTqYzMtbIJ65X8ER3v/gd0=,iv:OiZHXl78usGm95HxKnxOljcaKeVygJaRV8KzGQBhIWk=,tag:/NKPBZ8n9u+VbzsmbfCseA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
