apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
    namespace: kube-system
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:iqTJl+2QGHCXXpTCEX/JHhiBHEzi8yulJ0DeTdleiukrAHrtvIljWF9hxJgHp6NbX1ls/h4=,iv:DGxbF9gO35hYYOWVDUySswc7gYtFzEpY7zVNv9iCBdo=,tag:t/8sJlyClYrOkAGba6lTpA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUHpvVkVsVC9vc2RMek8x
            dTcvdmJCYy9pVkFTbm1ESjd2SUduL0NCV2dRCmZwVDMyelJ1QThPUTNBUkZSN1Vw
            TWVGdHhpV2JkdkJtaURQd29aUGRqOVkKLS0tIFRVQ2xicGZjNFZlcUxEUGQySWVu
            eFVySCtVRlI0TTZDSHRCZHhMQlpiRncKtXmdtQyaJjrHrfI5EV8LWvDDlgX2e8td
            LG9FlU0lSPHgCKdlVsJCgxsXZOodsa6obzZ/CEMH1ZkcgwFGOPX3Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T15:40:26Z"
    mac: ENC[AES256_GCM,data:d9Vv2jnkZ/UbUvJ/oycjus9ivEJ4DothXThv5nGWPM6346HVGBQgljsAlQAXV2ZtiAoKLg6Putdyk+REsWlGNiA5SanVuML3LZtUdiRDwgkUVF8cilk2cbO8Dhqx0PjX10Sm0r/s94eQXPWvcZsQK1ogIp9XKgYmYATiVHRt2Hg=,iv:hmpsgA9OJOoUmvx2TeEgPWVYwuorCh+tGZAaFioA/2Q=,tag:ASAKELsZ37n3E4NiKba8Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
