apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
    namespace: kube-system
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:iqTJl+2QGHCXXpTCEX/JHhiBHEzi8yulJ0DeTdleiukrAHrtvIljWF9hxJgHp6NbX1ls/h4=,iv:DGxbF9gO35hYYOWVDUySswc7gYtFzEpY7zVNv9iCBdo=,tag:t/8sJlyClYrOkAGba6lTpA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUHpvVkVsVC9vc2RMek8x
            dTcvdmJCYy9pVkFTbm1ESjd2SUduL0NCV2dRCmZwVDMyelJ1QThPUTNBUkZSN1Vw
            TWVGdHhpV2JkdkJtaURQd29aUGRqOVkKLS0tIFRVQ2xicGZjNFZlcUxEUGQySWVu
            eFVySCtVRlI0TTZDSHRCZHhMQlpiRncKtXmdtQyaJjrHrfI5EV8LWvDDlgX2e8td
            LG9FlU0lSPHgCKdlVsJCgxsXZOodsa6obzZ/CEMH1ZkcgwFGOPX3Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T15:19:36Z"
    mac: ENC[AES256_GCM,data:kgH/VtVoPrw2pg4uxDZGHk0vrdXYoQSKNUOKRMCmgVCX4YhMfDRkUm3uP8Tv9bmsFK6KbJILE08+BzFciR0a/Q4d03AP/qZgtGBZEhDAp49qajGQj/TAISQCCvq+lBUgZOZttRF4rX9HsyPk+DxWOF1zI177G+fj5Oo+G5aoeLo=,iv:TF+rP9J01z4C3mN2cZMckJEzRgGVT1d/UKqO3us8km4=,tag:vaMFFgOm2s8M6l1/hLO+QQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
