apiVersion: v1
kind: Secret
metadata:
    name: hetzner-dns-api
    namespace: kube-system
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:H7IfozP52qpDElIYcyIeGpHvxYeMiDhWygdwY0JEoaBIpHA5H6r1/yKkqZCI3IwKBZlpTSMuaYJ2mFoZDcYdEA==,iv:zT/toA9WWGwTigVhZXbjTaoLudqhOpXlD08e11qXOL8=,tag:rzVTFS22NX9mowTzm9qN6A==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV0JRSEVhUnJmRjhKM0Fj
            TklubXVaM1FyTFE1cVZZUjU2TGozK2F0NTBBCmgxc2w3d216RnpiTFZDQ2h3OEVm
            azZKcWRtVjhXaTFVeWV4RjZJc3BPbWMKLS0tIGZEdmg0OXhNUHdRSW1lVHJLcFRS
            N3ZVdEtuU0labXdoZy9GK05uQVdWdHMKG5dPpEdEH968anxIer++e1rXHJ3pDu4g
            IpjHZV0F+IgXTjCChFbaAOWzf48uohd1azTErj6DRHRLJ2d/T685SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T16:50:29Z"
    mac: ENC[AES256_GCM,data:crYUkVGvNFL6QgBBVoQa3ufoD9SXaJfDj0/8tx99DYzNQ0KkVM6n7JyEeJCMdO+mATeEgqRRs08IZreLKmBdJkEoIN0DoQ5R2PB7oBNKQXC0OfK9Wr6P8Tntm5Z/8LAce+NVAlyoHiYEtcy2BSb4B0XW9/yv7LUEbeKTXROzGPA=,iv:i7RK43YEYtDOT4b1Rj5qa0+z0Jz1Oih0HS2yP4noTaI=,tag:9CmrmuFJxG82eFGfft/R3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
