apiVersion: v1
kind: Secret
metadata:
    name: hetzner-dns-api
    namespace: kube-system
type: Opaque
stringData:
    HETZNER_TOKEN: ENC[AES256_GCM,data:wanBZsINOnMeUanK8YAvczI6zhvOwrFA2c0GJhK9gYAotZmKXHz4+NT0Wvkr7EyrZ+H0Z4KLcSeJXHf/ChVX3A==,iv:LniNfuJuxunpCclaGpJmN/wN/bi0hcPu7mYCj2laui8=,tag:Qo9yoJcUYWdieGCMZNsBhA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQTk5WDNTOVJvK0k2dHdW
            NGpZc2cyWHlYMHFOelQzR1Q4Y0N6YTI4NVR3CjFHajNlZTZUakEzNTlBNWFJU05W
            VzZ6d2RBWk8rU05ocHVtT0p0b2xJMkEKLS0tIDEwN2hVLzkrWDlRaitNdEh4NVc0
            ZHp4Z0tBYTI2bDlVZVAxaWVKR3NyRkUKbXBLT7bg4VNj5cg2Ecx2n9l7ILhURcJB
            dXV03hDcTY6haJ/VN4gDwTJDybaue2tqPM3SovwtEc5raRWLWF0A/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T16:31:53Z"
    mac: ENC[AES256_GCM,data:BQITzQEv65N641SCJbkq7TR1xwTgYFzqmzkh6ZCWxP2NqqK57P0b0esysXjRWgDCpkbs2tex8Xvc30dkpmiPWb6s6S4JMh0kNTypwmbp+kpU5n6+fuMtQHZQ/1VhP5yDsWq+ob3DTcJF4IX+lM+m7m96p6wPAJkJGW5QmEBnJ28=,iv:0+CmIes829Q+fapCTbTl2qXOAGziFp/FXu1tvQeNa1Y=,tag:nvdE+MQ3kRB6gBsw56gRng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
