apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: kube-system
      interval: 12h
  values:
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/mconfalonieri/external-dns-hetzner-webhook
          tag: v0.7.0
        env:
          - name: HETZNER_API_KEY
            valueFrom:
              secretKeyRef:
                name: hetzner-dns-api
                key: HOMELAB_HETZNER_DNS_API_KEY
          - name: USE_CLOUD_API
            value: "true"
          - name: LOG_LEVEL
            value: debug
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
    domainFilters:
      - "k8s-demo.de"
    policy: upsert-only
    txtOwnerId: "homelab"
    sources:
      - ingress
    interval: 2m
