apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: kube-system
      interval: 12h
  values:
    provider: hetzner
    env:
      - name: HETZNER_TOKEN
        valueFrom:
          secretKeyRef:
            name: hetzner-dns-api
            key: HOMELAB_HETZNER_DNS_API_KEY
    domainFilters:
      - "k8s-demo.de"
    policy: upsert-only
    txtOwnerId: "homelab"
    sources:
      - ingress
    interval: 2m
