apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wallabag-tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wallabag-tailscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wallabag-tailscale
subjects:
  - kind: ServiceAccount
    name: wallabag
