apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:pT0pCX59iBv3VwN8qF8g7Nez+FfTm/DAgYFI2EFuBuiCleM3hx7w+Ex8IuXO8qk+I7cwO0I=,iv:FylnlfQdzOYgl9Om9Sbxtzeq8TVcQUfNP6E+KohGYPM=,tag:M4+Sm/qtFPCvV/SbxgPzxg==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Y2lZMEhwN2tmZk1jMHo1
            K1RRQk5sMnJNTWRVS0NIVm9BUVRpUEZzMlc4Ck9OVW9LcGZkQzZGZXJoSFluQWg5
            Qm02bitRZTE4L05UejFuUThJRXFaYzQKLS0tIGl0LzI2TUo5UTlyNTVYenBmSVky
            WW5VSGdsWVRRQU9adStSbUlwd1czcmcKa0C3BLJwlp4kpc2lPwb/PNOyv5V3PPGy
            ZbRftziJTS2PYOt8al21faGJGPLqK5TZQF2Pn4e/J3iXypG4+RVi9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T09:31:21Z"
    mac: ENC[AES256_GCM,data:EgdYHCTZoBZslIBgWhG029vzZgEV1QKdfZ55/3PKTgFnWrlPfO5TMcHlTtwj6btVn6R+1y5TXomc+R2+jd4lLtoNxgEYA5ZaIx51qcxQvnfsBssUAhzogBoJp3jIyov4dFS/6HoCJxT/Kc4tPhbqJxxTQWkM6eMPjTpNxl2gt/s=,iv:Se7WPWO4fy3+C0Q/Tj3HIJyEeTiQrE7u1Vg5oQ40QoQ=,tag:fyswKE0vtm5jhY92Qzp+Xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
