apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - linkding
  - demo-api
  - cluster-dashboard
  - demo-django
  - freelance-radar
  - grafana
  - prometheus
  - node-exporter
  - kube-state-metrics
  - loki
  - promtail

  - wp-ai-chatbot-redirect
  - keycloak
  - no-deposit
  - external-dns
