apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 24h
  values:
    operatorConfig:
      extraEnv:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-authkey
              key: authkey
