apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:o1Kk0ZX/5ivQg1TciCIHqVY=,iv:ZSKvs24QoX8dPxo/D6jpr5jWM4tO6Du4IWHS8MD42m8=,tag:5l3CGGiHSj9NNyabTm28uA==,type:str]
    client_secret: ENC[AES256_GCM,data:ws5QzD0prn7aianlEKcToed/fioSjH8GaTopx4qhp7k0y7u81UYglpnektN1uro9L+eDGn2ETPDilY8cUWKg,iv:nc1UhDaZ1w/r2f1pwEEcMZc3d8uWdfVfr6keE3duo+s=,tag:5bTv7PIwL6ZrzA/D4nmgbA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OUl6STdrUU1oRzgydzd1
            TUpKS0Q0bEZ4UzEzQWJHNlNPS2lVZ3BlbkZVCnJGZDRzWWR6TU41WXNKaVdUM3ZN
            WnNTNjZ4b280ZmttUVlwL3ZTbVl6QzAKLS0tIE9IaCs3enI2eG5YTVRYZlgzZ1hk
            Mkd5Y3dXOWFINENOdXVMaHd5RTFUK28KrQg8bngrNmrAy7EnD6xXJh15bZY/l5s/
            Br7AkJsi9vJUba/ZARukOYlz66Xbo8mSYKZF4t0ZoUcFoIW9L9U1Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T19:26:51Z"
    mac: ENC[AES256_GCM,data:DruukD6NO8Fb0eeB0bootIHWz3p1K9n/ujSitTR4KCS+E3dfcxqBfa7ptv9wP5LzhQbOU+0cvaq984Lf5PdHtWTD8DHXCBcaN6x46jlfCyJgRG9oRNH2WiNiEbW9DrGUk4sU+4lnJ4UtmJLQZ+VZt9NY9Pw+oUs6HIFi+sxcwc0=,iv:jQxRCc/bCRcmcqesHJE0eDCQleW27SgDPR1ZnUtt6Q4=,tag:fnq223XzL6WMdRTqLzFafg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
