apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:hI2MA7qfEQLwEbxtlwrDYQY=,iv:r4FTUhxxUvKYHtJFISEA+MwrySUAgCuTeJowq/v3pfA=,tag:RThHcRbFdvwqK3BYEePdaQ==,type:str]
    client_secret: ENC[AES256_GCM,data:EGbKIS8Eu6FblTrl9lOn642FJH7ykVLMR3j+g35sV+zrNf12gFfCic2x9o7qsGsjd93cSRB+DxaVWZbcTpL8,iv:sF3DuZyV1UXNJq+wSZ2Cup6mrDF7WdhHxyBykJBC9Hk=,tag:dV7UdbBCsf/AhGxABeWPVg==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkamZtUTZVWWUxL2FSNEVG
            RlpCdFlhMUhaNVBWOThCNG11TjV1aXhUdGpFCnFub0J3eDN4TFNnVXpiUnd1YVk4
            OTlRdnlscElENmNQRkkxWHJXVi8rb3MKLS0tIEJjMTFSdms4SmVaYXFLU2p0SHZx
            RVR0a0dyeUk5TjVUR2Q0VGhkWWFGbUEK1nQxW3ho3hR6zHAnZUK23fRoxPviYQVU
            fJ7KziZa5ruhP6BxcfkNPkmyVeWrvEqlcbK4K4HQXqiKk/nIGScSaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T20:28:16Z"
    mac: ENC[AES256_GCM,data:/2WumPFUsMZWISp+92/UOEq1meN65hKYuwkmJwLmYiGgnRFNBZLB8vYFr6zwRaaIgRwFl5dTmMQ20MjRRT7H8GfIHaf7tsaOxQFJwz8ehZula2J3QXWD0lBHFCotVjabbM8mt54B5PyFEOYNSITSIoLI2gryCwppjCpy916t8rc=,iv:AhRAd0vWpuo71oOCgKaTPcVBfUBZHNC8kBEwpu8nG8Q=,tag:gqcWI/oXwDFeAX+Pw1s6lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
