apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: qlo-apps
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:oG7IUmHMdq1Z2QBIezc/n+lcv49m3064uQ==,iv:AFbRNtZTJoUm082PHPKNNYrSq5MzIT5UaJ3Ur2LXIo4=,tag:XrcFBXzAiW5Y41Ol4Bm+Fw==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:oW6oDupjZA==,iv:vTa1JTna25XzXD4x7Vs/5IdaqsybWDR7V2nwlxAp1As=,tag:YMEvxnDBoHF8MwxbGik7CA==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:aghZzQnm7Q==,iv:/kBvd2TWDYKlczP89CjTNS1Kf9mHmDBNfWV8mi/EgJI=,tag:RzVFLAf1QcYSyuwOsegdvg==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:2kEOTXpeQJ8mN91zk0Nx/sjQGteuUBGEnA==,iv:RL023h4pGWNUyzKp/GvIc9+dWyvQjWCCMvv6ZF1yyOI=,tag:E46/vFn3HJis+GwQA4sgxg==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcks0d3VLTzVTUGNpNkl6
            N25NaVI5QWxheWk4RDV0TVBKK2k5RlhFZW1ZCkFPVFQ5UGpOSVRteVdGV1ZpMHJp
            cG9HSXFYdHFicEtxVWxmRkxGaTd1dDgKLS0tIGxhOThwQXhpZmpUaXV4K0MyQ0VP
            ZmJsS0ZuUTAxWVR2SXl3RnlZQWZ4SVkKtsbmqc7Cnjj1uGFM3HkJtTra5cFnFeAQ
            qCkFTakpAk8QzpUMF4ZZgoSkhUQXkEPmqZrN+cDPAOKSczVabwHswg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T14:49:06Z"
    mac: ENC[AES256_GCM,data:zWiqcwOMgwOIlQxqQ0QLz5Bw4Nej0NyZ1AMTryacAex8hoDY4o6b3oofQJDQljJwcIEgK+/l6/Y0xc9ZX9dXY/OH5teZnWZcaT1BqX63Z2ybvhIIHVj0l/vId4sdWiMvkk4kPx7Aj7bZ7GschrIa18rEZb7k/AqNjjo3HJVzAJ0=,iv:7lmgaYijRM1JPVoawCa/2K6krkGtaFDczUsdODfiKmk=,tag:Nn0QZ5QvQ2HDuB+Ti/2asA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: qlo-apps-secret
    namespace: qlo-apps
type: Opaque
stringData:
    ADMIN_MAIL: ENC[AES256_GCM,data:drgOD3YQyXqNOkf7ysuTNXGhND+OzPwyuYsjFA==,iv:UDem2zgXc1dKc6tRGBl1MnPrGtbu6COnoheDLaE++u4=,tag:Bk6VzBn4CjO97ASPDRFioQ==,type:str]
    ADMIN_PASSWD: ENC[AES256_GCM,data:u8m0on6f0qhEJMHa01uvmj1J+J0x6fiCkA==,iv:JEOMHHw+K803MfIe8RGjnruLbXjrYI42BgR5gHWgZmQ=,tag:9BgrCNWF7Lljg/49xsRuTA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcks0d3VLTzVTUGNpNkl6
            N25NaVI5QWxheWk4RDV0TVBKK2k5RlhFZW1ZCkFPVFQ5UGpOSVRteVdGV1ZpMHJp
            cG9HSXFYdHFicEtxVWxmRkxGaTd1dDgKLS0tIGxhOThwQXhpZmpUaXV4K0MyQ0VP
            ZmJsS0ZuUTAxWVR2SXl3RnlZQWZ4SVkKtsbmqc7Cnjj1uGFM3HkJtTra5cFnFeAQ
            qCkFTakpAk8QzpUMF4ZZgoSkhUQXkEPmqZrN+cDPAOKSczVabwHswg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T14:49:06Z"
    mac: ENC[AES256_GCM,data:zWiqcwOMgwOIlQxqQ0QLz5Bw4Nej0NyZ1AMTryacAex8hoDY4o6b3oofQJDQljJwcIEgK+/l6/Y0xc9ZX9dXY/OH5teZnWZcaT1BqX63Z2ybvhIIHVj0l/vId4sdWiMvkk4kPx7Aj7bZ7GschrIa18rEZb7k/AqNjjo3HJVzAJ0=,iv:7lmgaYijRM1JPVoawCa/2K6krkGtaFDczUsdODfiKmk=,tag:Nn0QZ5QvQ2HDuB+Ti/2asA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
