apiVersion: apps.kubetest.uk/v1
kind: WebApp
metadata:
  name: webapp-sample
  namespace: webapp-operator-system
  labels:
    app.kubernetes.io/name: webapp-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  image: nginx:1.25
  replicas: 2
  port: 80
