apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:WYFRKtcf1ryhLAfT+gFPaexD8RlHeGduiXFCjeZh8ulzwEyhIl0/oXNYk+9xi5uXoJ+D3To=,iv:Uafb/AvSuIrBbt7Uv2S4fEcF9lboWaIPpVwU+X9ISik=,tag:0FBZBgIPvUD0fKlyQMIGkg==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWGFEVU9Oc05BMGUva1pz
            YUsrYlhJWlZ4dzNhMllNUVo2S3I2SCt4UHhNCmpIWGJPOXA1WDJ1VkNOUWIwK0Z1
            VHBLajhmQzZZWjRVSitJRGZBODc5cHcKLS0tIFY0OGQvOTFTU2c1Ulg5dncwbWFo
            bGl2VTFpQ1NsaGRKYkp1eG9Za25YY3MKsD2SYjK2UBeWhFOM5N2Zu2g2ipuj87aD
            /ejVz1y+K9sf1yosY2Xch5Ychehm4lk+KojifsVAQOvp/q79fT4MVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T11:51:00Z"
    mac: ENC[AES256_GCM,data:De8cK6rap3S+Yg5tF2atyHje5+x0yijBz4cNx9PYCrx2RxnXBzDrKYYQlDOkPStTe4WdUtipylZCmmbGrw1J6rDyBqAU4hTewrT0eoeU/nMwrYvNSdCg4PdKo0F/pQH6T+Tnw8GAMWr2/AETy3VBc85ytxbAhdJ+EZboK3hHXBg=,iv:KlmgBySKwfQg5CLY9enlYZyju+lMPbUGP3pEpnECZCQ=,tag:9pLxqCkz3KUc12EtPkxe0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
